### PR TITLE
Create hugo.yml

### PR DESCRIPTION
**Pull request by loleg**
This allows us to automatically build, or at least stage for testing, the site using GitHub Actions. 

- https://github.com/marketplace/actions/hugo-setup
- https://gohugo.io/hosting-and-deployment/hosting-on-github/

### CODE REVIEW

**Comment by loleg** [comment]
Yes, I know we already have Travis CI for that. But this is much faster and easier to maintain, plus I'm seeing [builds failing](https://travis-ci.org/github/make-zurich/website/builds/723286505) and no way to easily preview Pull Requests, so I thought to suggest this.

**Review by gonzalocasas — CHANGES_REQUESTED** [review]
Cool! Thanks!!

Three small comments:
- Please delete the `.travis.yml` file otherwise we will deploy twice per commit ;)
- Shouldn't the `deploy` step only occur on `master`? Otherwise this would publish PRs while they are worked on...?
- The `Deploy` step needs to point to the correct repo (this is source and github pages is on `make-zurich/make-zurich.github.io`), check the travis file for details.

**Comment by gonzalocasas** [comment]
> Yes, I know we already have Travis CI for that. But this is much faster and easier to maintain, plus I'm seeing [builds failing](https://travis-ci.org/github/make-zurich/website/builds/723286505) and no way to easily preview Pull Requests, so I thought to suggest this.

Yep, I'm totally for for switching to GH Actions. I've been meaning to do this for a while, but never had the time.

**Comment by gonzalocasas** [comment]
Ah the PR preview is a good point. Maybe we could have two different jobs, one that runs on master only and publishes with the action to the built website repo, and a different one for PRs only that pushes to the github pages of this one for a sort of staging preview?

**Comment by loleg** [comment]
Agree with everything. Please take over from here :)

**Comment by gonzalocasas** [comment]
@loleg thanks for this one! I merged it now, but I didn't have time to do the "deploy to staging" part, so, for now, it replaces the old Travis build, and it is certainly much much faster.

**Pull request merged**
